version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/.github/workflows/*.yml"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10 